name: .NET

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_PACKAGE_PATH: .

jobs:
  build:    
    defaults:
      run:
        working-directory: .net-src/ProfilePictureResizer/PortraitImageResizer.Serverless/      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: dotnet build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o '${{ env.AZURE_PACKAGE_PATH }}/PUBLISHED' 
      
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.1.8
      with:
        # Name of the Azure Function App
        app-name: PortraitImageResizer
        # Path to package or folder. *.zip or a folder to deploy
        package: ${{ env.AZURE_PACKAGE_PATH }}/PUBLISHED
        # Function app slot to be deploy to        
        # Publish profile (*.publishsettings) file contents with web deploy secrets
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
